unclassified:
  gitSCM:
    globalConfigName: "dythia102"
    globalConfigEmail: "dythia102@example.com"
  location:
    url: ${JENKINS_URL}
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github-token
              username: dythia102
              password: ${GITHUB_TOKEN}
              description: GitHub Personal Access Token
jobs:
  - script: >
      freeStyleJob('docker-info') {
        description('Manual job to execute docker info')
        logRotator {
          numToKeep(10)
        }
        steps {
          shell('docker info')
          shell('pwd')
          shell('ls -la')
          shell('git')
        }
      }
  - script: >
      freeStyleJob('docker-info-hook') {
        description('Job to execute docker info triggered by GitHub webhook')
        logRotator {
          numToKeep(10)
        }
        properties {
          githubProjectProperty {
            projectUrlStr('https://github.com/dythia102/coding-test/')
            displayName('')
          }
        }
        scm {
          git {
            remote {
              url('https://github.com/dythia102/coding-test.git')
              credentials('github-token')
            }
            branch('*/production')
          }
        }
        triggers {
          githubPush()
        }
        steps {
          shell('docker info')
        }
      }