FROM jenkins/jenkins:lts-alpine-jdk21

USER root

# Install Docker CLI
RUN apk update && \
    apk add --no-cache docker-cli && \
    addgroup -S docker || true && \
    addgroup jenkins docker

# Install Jenkins plugins
RUN jenkins-plugin-cli --plugins \
    configuration-as-code \
    workflow-aggregator \
    job-dsl \
    docker-workflow \
    git \
    github \
    github-branch-source

USER jenkins