services:
  backend:
    image: dythia102/sales-ai-backend:latest
    working_dir: /app
    environment:
      AI_API_KEY: "xxxxxxxxxxxxxxx"
      APP_TITLE: "Sales AI (Dev)"
      APP_DESCRIPTION: "Sales Rep Intelligence API"
      APP_VERSION: "1.0.0"
      AI_PROVIDER: "openrouter"
      AI_MODEL: "mistralai/mixtral-8x7b-instruct"
      AI_API_BASE: "https://openrouter.ai/api/v1"
      USE_AI: "true"
      FRONTEND_URL: "http://52.74.52.230:3000"
    command: >
      sh -c "
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      placement:
        constraints:
          - node.labels.name == node00
    networks:
      - sales-ai_default

  frontend:
    image: dythia102/sales-ai-frontend:latest
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_URL: "http://52.74.52.230:8000"
    command: >
      sh -c "
        npm run start
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      placement:
        constraints:
          - node.labels.name == node00
    networks:
      - sales-ai_default

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
      placement:
        constraints:
          - node.role == manager
    networks:
      - sales-ai_default
