services:
  backend:
    image: python:3.11-alpine
    container_name: sales-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        apk add --no-cache gcc musl-dev libffi-dev python3-dev &&
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
  frontend:
    image: node:18-alpine
    container_name: sales-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
