services:
  jenkins:
    build:
      context: ./devops
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=Asia/Jakarta
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      - CASC_ENV=true
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./devops/jenkins/jenkins_home:/var/jenkins_home
      - ./devops/jenkins/casc_configs:/var/jenkins_home/casc_configs
      - ./devops/jenkins/jobs:/var/jenkins_home/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - ./devops/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADMIN_USERNAME=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
