services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - ./devops/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADMIN_USERNAME=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
