jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${ADMIN_USER}
          password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: http://52.74.52.230:8080/

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-credentials"
              username: "${GITHUB_USER}"
              password: "${GITHUB_TOKEN}"
              description: "GitHub PAT for webhook/pipeline access"

jobs:
  - script: >
      pipelineJob('docker-info') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                stages {
                  stage('Docker Info') {
                    steps {
                      sh 'docker info'
                    }
                  }
                }
              }
            ''')
            sandbox()
          }
        }
      }
