jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${ADMIN_USER}
          password: ${ADMIN_PASSWORD}

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: http://52.74.52.230:8080/

jobs:
  - script: >
      pipelineJob('docker-info-prod-hook') {
        description('Triggered by GitHub Webhook on push to production branch')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  github('dythia102/coding-test', 'https')
                }
                branches('*/production')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        properties {
          githubProjectUrl('https://github.com/dythia102/coding-test')
        }
        triggers {
          githubPush()
        }
      }

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-credentials"
              username: "${GITHUB_USER}"
              password: "${GITHUB_TOKEN}"
              description: "GitHub PAT for webhook/pipeline access"

