jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${ADMIN_USER}
          password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: http://localhost:8080/

# ✅ This block must be at the root level — not inside 'jenkins:'
jobs:
  - script: >
      freeStyleJob('docker-info') {
        steps {
          shell('docker info')
        }
      }
  - script: >
        pipelineJob('docker-info-prod-hook') {
          definition {
            cpsScm {
              scm {
                git {
                  remote {
                    url('https://github.com/dythia102/coding-test.git')
                  }
                  branches('*/production')
                }
              }
              scriptPath('Jenkinsfile') // Or use inline script instead
            }
          }
          triggers {
            githubPush()
          }
        }

