jenkins:
  systemMessage: "Jenkins Configured via CASC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${ADMIN_USER}"
          password: "${ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: true
unclassified:
  gitHubPluginConfig:
    hookUrl: "http://52.74.52.230:8080/github-webhook/"
    configs:
      - name: "github"
        apiUrl: "https://api.github.com"
        credentialsId: "github-pat"
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "github-pat"
              description: "GitHub Personal Access Token"
              secret: "${GITHUB_PAT}"
jobs:
  - script: |
      job('Seed-Job') {
        description('Seed job to create other jobs using Job DSL')
        scm {
          git {
            remote {
              github('dythia102/coding-test')
              credentials('github-pat')
            }
            branch('main')
          }
        }
        steps {
          dsl {
            external('/var/jenkins_home/jobs/job-dsl-seed.groovy')
            removeAction('DELETE')
          }
        }
      }