unclassified:
  globalConfigFiles:
    configs:
      - id: "global-maven-settings"
        name: "global-maven-settings"
        comment: "Global Maven settings"
        content: ""
  gitSCM:
    globalConfigName: "dythia102"
    globalConfigEmail: "dythia102@example.com"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github-token
              username: dythia102
              password: ${GITHUB_TOKEN}
              description: GitHub Personal Access Token
jobs:
  - script: >
      freestyleJob('Manual_Docker_Info') {
        description('Manual job to execute docker info')
        logRotator {
          numToKeep(10)
        }
        steps {
          shell('docker info')
        }
      }
  - script: >
      freestyleJob('GitHub_Webhook_Docker_Info') {
        description('Job to execute docker info triggered by GitHub webhook')
        logRotator {
          numToKeep(10)
        }
        properties {
          githubProjectProperty {
            projectUrl('https://github.com/dythia102/coding-test/')
            displayName('')
          }
        }
        scm {
          git {
            remote {
              url('https://github.com/dythia102/coding-test.git')
              credentials('github-token')
            }
            branch('*/main')
          }
        }
        triggers {
          githubPush()
        }
        steps {
          shell('docker info')
        }
      }