services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ./jenkins/casc_configs:/var/jenkins_home/casc_configs
      - ./jenkins/jobs:/var/jenkins_home/jobs
      - /var/run/docker.sock:/var/run/docker.sock # 🔥 Docker socket
    privileged: true
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
